AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
